name: Google Chat Notification

on:
  push:
    branches:
      - main

jobs:
  google-chat-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification to Google Chat
        run: |
          cat <<EOF > payload.json
          {
            "text": "ðŸš€ *Aircon Update: New Push to asset-management-system*\n\n*Branch:* ${{ github.ref_name }}\n*Commit:* ${{ github.event.head_commit.message }}\n*Author:* ${{ github.actor }}\n\n[View Commit](${{ github.event.head_commit.url }})"
          }
          EOF
          curl -X POST -H "Content-Type: application/json" -d @payload.json "${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}"
